import { Venue, Task } from "./types";

function task(id: string, venueId: string, type: Task["type"], question: string, options?: string[]): Task {
  return { id, type, question, options, venueId };
}

export const MOCK_VENUES: Venue[] = [
  {
    id: "v1", name: "Koffee", address: "1 La Vuelta, Orinda, CA",
    lat: 37.8784, lng: -122.1796, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [task("t1", "v1", "confirm_category", "Is 'Coffee Shop' the correct category for this venue?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-555-6578",
      hours: [
        { day: "Mon - Thu", hours: "9 am - 8 pm" },
        { day: "Fri", hours: "10 am - 8 pm" },
        { day: "Sat", hours: "9 am - 11 pm" },
        { day: "Sun", hours: "9 am - 11 pm" },
      ],
      website: "http://www.koffee-orinda.com",
      facebook: "koffeecafe",
      instagram: "@koffeecafe",
      features: ["Reservation", "Credit card: Master, Visa, AMEX", "Outdoor seating"],
      fsqPlaceId: "4aff17aaf964a520143422e3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 1,
      suggestedAddress: "10 La Vuelta, Orinda, CA",
      suggestedPhone: "415-555-6573",
      suggestedHours: [
        { day: "Mon - Thu", hours: "9 am - 8 pm" },
        { day: "Fri", hours: "10 am - 8 pm" },
        { day: "Sat", hours: "9 am - 11 pm" },
        { day: "Sun", hours: "9 am - 11 pm" },
      ],
    },
  },
  {
    id: "v2", name: "901 Columbus Cafe", address: "901 Columbus Ave, San Francisco, CA",
    lat: 37.8005, lng: -122.4112, category: "Cafe",
    tags: ["Flagged", "Categories", "Chains"],
    tasks: [
      task("t2", "v2", "confirm_category", "Is 'Cafe' the correct category?", ["Yes", "No", "Not sure"]),
      task("t3", "v2", "verify_address", "Is '901 Columbus Ave' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-986-1886",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 5 pm" },
      ],
      website: "http://www.901columbuscafe.com",
      facebook: "901columbusCafe",
      instagram: "@901columbus",
      features: ["Wi-Fi", "Credit card: Visa, AMEX"],
      fsqPlaceId: "4bf58dd8d48988d1e0931735",
      uniqueVisitors: 3,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedAddress: "901 Columbus Ave, Suite B, San Francisco, CA",
      suggestedPhone: "415-986-1890",
      suggestedHours: [
        { day: "Mon - Fri", hours: "6:30 am - 6 pm" },
        { day: "Sat - Sun", hours: "7 am - 5 pm" },
      ],
    },
  },
  {
    id: "v3", name: "Baja Cali Taqueria & Grill", address: "1 La Vuelta, Orinda, CA",
    lat: 37.8801, lng: -122.1820, category: "Mexican Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [task("t4", "v3", "confirm_hours", "Are the hours Mon-Sat 9AM-9PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "925-254-1331",
      hours: [
        { day: "Mon - Sat", hours: "9 am - 9 pm" },
        { day: "Sun", hours: "10 am - 8 pm" },
      ],
      website: "http://www.bajacalitaqueria.com",
      instagram: "@bajacalitaqueria",
      features: ["Outdoor seating", "Takeout", "Credit card: Visa, Master"],
      fsqPlaceId: "4c2c0732f964a5209ea93ee3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedHours: [
        { day: "Mon - Sat", hours: "10 am - 9 pm" },
        { day: "Sun", hours: "10 am - 8 pm" },
      ],
    },
  },
  {
    id: "v4", name: "Tartine Bakery", address: "600 Guerrero St, San Francisco, CA",
    lat: 37.7613, lng: -122.4243, category: "Bakery",
    tags: ["Details"],
    tasks: [
      task("t5", "v4", "verify_address", "Is '600 Guerrero St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t5b", "v4", "confirm_hours", "Are the hours 8AM-7PM Mon-Fri correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-487-2600",
      hours: [
        { day: "Mon - Fri", hours: "8 am - 7 pm" },
        { day: "Sat - Sun", hours: "9 am - 8 pm" },
      ],
      website: "http://www.tartinebakery.com",
      instagram: "@tartinebakery",
      features: ["Credit card: Master, Visa, AMEX", "Outdoor seating"],
      fsqPlaceId: "40a55d80f964a52020f31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
      suggestedAddress: "602 Guerrero St, San Francisco, CA",
    },
  },
  {
    id: "v5", name: "Blue Bottle Coffee", address: "66 Mint St, San Francisco, CA",
    lat: 37.7824, lng: -122.4058, category: "Coffee Shop",
    tags: ["Chains", "Categories"],
    tasks: [task("t6", "v5", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "510-653-3394",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 5 pm" },
      ],
      website: "http://www.bluebottlecoffee.com",
      facebook: "bluebottlecoffee",
      instagram: "@bluebottle",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4b12c5f4f964a5204ba723e3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
    },
  },
  {
    id: "v6", name: "Bi-Rite Creamery", address: "3692 18th St, San Francisco, CA",
    lat: 37.7617, lng: -122.4256, category: "Ice Cream Shop",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t7", "v6", "confirm_hours", "Are hours 11AM-10PM daily correct?", ["Yes", "No", "Not sure"]),
      task("t7b", "v6", "verify_address", "Is '3692 18th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-626-5600",
      hours: [{ day: "Daily", hours: "11 am - 10 pm" }],
      website: "http://www.biritecreamery.com",
      instagram: "@biritecreamery",
      features: ["Credit card: Visa, Master", "Outdoor seating"],
      fsqPlaceId: "49d4fb90f964a520b85d1fe3",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "3692 18th St, Suite A, San Francisco, CA",
    },
  },
  {
    id: "v7", name: "Foreign Cinema", address: "2534 Mission St, San Francisco, CA",
    lat: 37.7568, lng: -122.4186, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t8", "v7", "confirm_category", "Is 'Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-648-7600",
      hours: [
        { day: "Mon - Thu", hours: "5:30 pm - 10 pm" },
        { day: "Fri - Sat", hours: "5:30 pm - 11 pm" },
        { day: "Sun", hours: "11 am - 3 pm, 5:30 pm - 10 pm" },
      ],
      website: "http://www.foreigncinema.com",
      facebook: "foreigncinema",
      instagram: "@foreigncinema",
      features: ["Reservation", "Outdoor seating", "Full bar"],
      fsqPlaceId: "3fd66200f964a52032e61ee3",
      uniqueVisitors: 4,
      totalCheckins: 5,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v8", name: "Dolores Park Cafe", address: "501 Dolores St, San Francisco, CA",
    lat: 37.7610, lng: -122.4272, category: "Cafe",
    tags: ["Flagged"],
    tasks: [
      task("t9", "v8", "fix_coordinates", "Does the pin location look correct on the map?", ["Yes", "No", "Not sure"]),
      task("t9b", "v8", "confirm_category", "Is 'Cafe' the correct category?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-621-2936",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 7 pm" },
        { day: "Sat - Sun", hours: "8 am - 7 pm" },
      ],
      features: ["Wi-Fi", "Outdoor seating"],
      fsqPlaceId: "42377700f964a52069221fe3",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
      suggestedAddress: "501 Dolores St #1, San Francisco, CA",
    },
  },
  {
    id: "v9", name: "Delfina", address: "3621 18th St, San Francisco, CA",
    lat: 37.7618, lng: -122.4247, category: "Italian Restaurant",
    tags: ["Categories"],
    tasks: [task("t10", "v9", "verify_address", "Is '3621 18th St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
    detail: {
      phone: "415-552-4055",
      hours: [
        { day: "Tue - Sat", hours: "5:30 pm - 10 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
      website: "http://www.delfinasf.com",
      instagram: "@delfinarestaurant",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a520bde31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v10", name: "Philz Coffee", address: "3101 24th St, San Francisco, CA",
    lat: 37.7526, lng: -122.4184, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [
      task("t11", "v10", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"]),
      task("t11b", "v10", "verify_address", "Is '3101 24th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-875-9370",
      hours: [
        { day: "Mon - Fri", hours: "6 am - 7:30 pm" },
        { day: "Sat - Sun", hours: "6:30 am - 7:30 pm" },
      ],
      website: "http://www.philzcoffee.com",
      facebook: "philzcoffee",
      instagram: "@philzcoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4a83a0b6f964a520f4fb1fe3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 5,
      suggestedPhone: "415-875-9371",
    },
  },
  {
    id: "v11", name: "La Taqueria", address: "2889 Mission St, San Francisco, CA",
    lat: 37.7508, lng: -122.4181, category: "Taqueria",
    tags: ["Details", "Categories"],
    tasks: [task("t12", "v11", "confirm_category", "Is 'Taqueria' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-285-7117",
      hours: [{ day: "Daily", hours: "11 am - 9 pm" }],
      features: ["Cash only", "Outdoor seating"],
      fsqPlaceId: "3fd66200f964a520b1e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
    },
  },
  {
    id: "v12", name: "Sightglass Coffee", address: "270 7th St, San Francisco, CA",
    lat: 37.7772, lng: -122.4068, category: "Coffee Shop",
    tags: ["Chains", "Details"],
    tasks: [
      task("t13", "v12", "verify_address", "Is '270 7th St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t13b", "v12", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-861-1313",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 6 pm" },
      ],
      website: "http://www.sightglasscoffee.com",
      instagram: "@sightglasscoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master"],
      fsqPlaceId: "4c04bbd8a1010f477dba0ef2",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "270 7th St, Floor 1, San Francisco, CA",
    },
  },
  {
    id: "v13", name: "Zuni Cafe", address: "1658 Market St, San Francisco, CA",
    lat: 37.7736, lng: -122.4215, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t14", "v13", "confirm_hours", "Are hours Tue-Sun 11:30AM-11PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-552-2522",
      hours: [
        { day: "Tue - Sun", hours: "11:30 am - 11 pm" },
        { day: "Mon", hours: "Closed" },
      ],
      website: "http://www.zunicafe.com",
      facebook: "zunicafe",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a52096e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
      suggestedHours: [
        { day: "Tue - Thu", hours: "11:30 am - 10 pm" },
        { day: "Fri - Sat", hours: "11:30 am - 11 pm" },
        { day: "Sun", hours: "11 am - 10 pm" },
        { day: "Mon", hours: "Closed" },
      ],
    },
  },
  {
    id: "v14", name: "Ritual Coffee Roasters", address: "1026 Valencia St, San Francisco, CA",
    lat: 37.7565, lng: -122.4214, category: "Coffee Shop",
    tags: ["Categories"],
    tasks: [task("t15", "v14", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-641-1024",
      hours: [
        { day: "Mon - Fri", hours: "6:30 am - 7 pm" },
        { day: "Sat - Sun", hours: "7 am - 7 pm" },
      ],
      website: "http://www.ritualroasters.com",
      instagram: "@ritualcoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master"],
      fsqPlaceId: "42d4b3e0f964a520cd251fe3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v15", name: "Nopa", address: "560 Divisadero St, San Francisco, CA",
    lat: 37.7745, lng: -122.4378, category: "Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t16", "v15", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"]),
      task("t16b", "v15", "confirm_hours", "Are hours Mon-Fri 6PM-1AM correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-864-8643",
      hours: [
        { day: "Mon - Fri", hours: "6 pm - 1 am" },
        { day: "Sat - Sun", hours: "11 am - 1 am" },
      ],
      website: "http://www.nopasf.com",
      facebook: "nopasf",
      instagram: "@nopasf",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "44b22a15f964a520f7321fe3",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedHours: [
        { day: "Mon - Fri", hours: "5 pm - 12 am" },
        { day: "Sat - Sun", hours: "11 am - 12 am" },
      ],
    },
  },
  {
    id: "v16", name: "Flour + Water", address: "2401 Harrison St, San Francisco, CA",
    lat: 37.7590, lng: -122.4132, category: "Italian Restaurant",
    tags: ["Details"],
    tasks: [task("t17", "v16", "verify_address", "Is '2401 Harrison St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-826-7000",
      hours: [
        { day: "Mon - Thu", hours: "5:30 pm - 10 pm" },
        { day: "Fri - Sat", hours: "5:30 pm - 10:30 pm" },
        { day: "Sun", hours: "5 pm - 9:30 pm" },
      ],
      website: "http://www.flourandwater.com",
      instagram: "@flourandwater",
      features: ["Reservation", "Full bar"],
      fsqPlaceId: "4bcc0390cc8cd13a2e1f8cf7",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "2401 Harrison St, San Francisco, CA 94110",
    },
  },
  {
    id: "v17", name: "Trick Dog", address: "3010 20th St, San Francisco, CA",
    lat: 37.7586, lng: -122.4220, category: "Bar",
    tags: ["Categories", "Flagged"],
    tasks: [task("t18", "v17", "confirm_category", "Is 'Bar' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-471-2999",
      hours: [{ day: "Daily", hours: "3 pm - 2 am" }],
      website: "http://www.trickdogbar.com",
      instagram: "@trickdogbar",
      features: ["Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "51756e5de4b0bb59b25d062a",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v18", name: "Humphry Slocombe", address: "2790 Harrison St, San Francisco, CA",
    lat: 37.7536, lng: -122.4133, category: "Ice Cream Shop",
    tags: ["Details"],
    tasks: [task("t19", "v18", "confirm_hours", "Are hours 12PM-9PM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
    detail: {
      phone: "415-550-6971",
      hours: [{ day: "Daily", hours: "12 pm - 9 pm" }],
      website: "http://www.humphryslocombe.com",
      facebook: "humphryslocombe",
      instagram: "@humphryslocombe",
      features: ["Credit card: Visa, Master"],
      fsqPlaceId: "4ad4c05ff964a520b7f220e3",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v19", name: "Anchor Brewing", address: "1705 Mariposa St, San Francisco, CA",
    lat: 37.7638, lng: -122.3979, category: "Brewery",
    tags: ["Chains", "Attributes"],
    tasks: [task("t20", "v19", "confirm_category", "Is 'Brewery' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-863-8350",
      hours: [
        { day: "Mon - Fri", hours: "12 pm - 9 pm" },
        { day: "Sat", hours: "11 am - 9 pm" },
        { day: "Sun", hours: "Closed" },
      ],
      website: "http://www.anchorbrewing.com",
      facebook: "anchorbrewing",
      instagram: "@anchorbrewing",
      features: ["Taproom", "Tours", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a52096e81ee3",
      uniqueVisitors: 3,
      totalCheckins: 3,
      visitedLast60Days: 1,
    },
  },
  {
    id: "v20", name: "Dandelion Chocolate", address: "740 Valencia St, San Francisco, CA",
    lat: 37.7609, lng: -122.4216, category: "Chocolate Shop",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t21", "v20", "verify_address", "Is '740 Valencia St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t21b", "v20", "confirm_hours", "Are hours 10AM-9PM daily correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-349-0942",
      hours: [{ day: "Daily", hours: "10 am - 9 pm" }],
      website: "http://www.dandelionchocolate.com",
      facebook: "dandelionchocolate",
      instagram: "@dandelionchocolate",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4fb3c2fbe4b0d0766b56fb8b",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "740 Valencia St, San Francisco, CA 94110",
    },
  },
  {
    id: "v21", name: "Nopalito", address: "306 Broderick St, San Francisco, CA",
    lat: 37.7725, lng: -122.4397, category: "Mexican Restaurant",
    tags: ["Categories"],
    tasks: [task("t22", "v21", "confirm_category", "Is 'Mexican Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-437-0303",
      hours: [
        { day: "Mon - Fri", hours: "11:30 am - 10 pm" },
        { day: "Sat - Sun", hours: "11 am - 10 pm" },
      ],
      website: "http://www.nopalitosf.com",
      instagram: "@nopalitosf",
      features: ["Reservation", "Credit card: Visa, Master"],
      fsqPlaceId: "4b88ddbaf964a520953932e3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v22", name: "Piccino", address: "1001 Minnesota St, San Francisco, CA",
    lat: 37.7554, lng: -122.3897, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t23", "v22", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-824-4224",
      hours: [
        { day: "Tue - Sat", hours: "11:30 am - 9 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
      website: "http://www.piccinocafe.com",
      instagram: "@piccinocafe",
      features: ["Outdoor seating", "Credit card: Visa, Master"],
      fsqPlaceId: "43cbabd0f964a520cd2d1fe3",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
    },
  },
  {
    id: "v23", name: "Lazy Bear", address: "3416 19th St, San Francisco, CA",
    lat: 37.7600, lng: -122.4220, category: "Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [task("t24", "v23", "confirm_hours", "Are hours Wed-Sun 6PM-10PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-874-9921",
      hours: [
        { day: "Wed - Sun", hours: "6 pm - 10 pm" },
        { day: "Mon - Tue", hours: "Closed" },
      ],
      website: "http://www.lazybearsf.com",
      instagram: "@lazybearsf",
      features: ["Reservation required", "Tasting menu", "Full bar"],
      fsqPlaceId: "53e6e48e498ea3e1fde0bcdf",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
      suggestedHours: [
        { day: "Wed - Sun", hours: "5:30 pm - 10 pm" },
        { day: "Mon - Tue", hours: "Closed" },
      ],
    },
  },
  {
    id: "v24", name: "Craftsman and Wolves", address: "746 Valencia St, San Francisco, CA",
    lat: 37.7607, lng: -122.4217, category: "Bakery",
    tags: ["Categories", "Details"],
    tasks: [task("t25", "v24", "confirm_category", "Is 'Bakery' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-913-7713",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 4 pm" },
        { day: "Sat - Sun", hours: "8 am - 4 pm" },
      ],
      website: "http://www.craftsman-wolves.com",
      instagram: "@craftsmanwolves",
      features: ["Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "513fd6c8e4b0d49fdd0f50c0",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v25", name: "State Bird Provisions", address: "1529 Fillmore St, San Francisco, CA",
    lat: 37.7835, lng: -122.4324, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t26", "v25", "verify_address", "Is '1529 Fillmore St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-795-1272",
      hours: [
        { day: "Mon - Sat", hours: "5:30 pm - 10 pm" },
        { day: "Sun", hours: "Closed" },
      ],
      website: "http://www.statebirdsf.com",
      instagram: "@statebirdprovisions",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "5065ca35e4b0a8f1e19a8fba",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 1,
      suggestedAddress: "1529 Fillmore St, San Francisco, CA 94115",
    },
  },
  {
    id: "v26", name: "El Farolito", address: "2779 Mission St, San Francisco, CA",
    lat: 37.7521, lng: -122.4181, category: "Taqueria",
    tags: ["Flagged", "Details"],
    tasks: [task("t27", "v26", "confirm_category", "Is 'Taqueria' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-824-7877",
      hours: [{ day: "Daily", hours: "10 am - 3 am" }],
      features: ["Cash preferred", "Late night"],
      fsqPlaceId: "3fd66200f964a52099e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
    },
  },
  {
    id: "v27", name: "Toronado", address: "547 Haight St, San Francisco, CA",
    lat: 37.7717, lng: -122.4316, category: "Bar",
    tags: ["Categories"],
    tasks: [task("t28", "v27", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-863-2276",
      hours: [{ day: "Daily", hours: "11:30 am - 2 am" }],
      website: "http://www.toronado.com",
      features: ["Cash only", "Craft beer"],
      fsqPlaceId: "3fd66200f964a52082e31ee3",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 2,
    },
  },
  {
    id: "v28", name: "Four Barrel Coffee", address: "375 Valencia St, San Francisco, CA",
    lat: 37.7664, lng: -122.4220, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [task("t29", "v28", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-252-0800",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 6 pm" },
      ],
      website: "http://www.fourbarrelcoffee.com",
      instagram: "@fourbarrelcoffee",
      features: ["Wi-Fi", "Outdoor seating"],
      fsqPlaceId: "4a93fbb8f964a52023591fe3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
    },
  },
  {
    id: "v29", name: "Mitchell's Ice Cream", address: "688 San Jose Ave, San Francisco, CA",
    lat: 37.7440, lng: -122.4245, category: "Ice Cream Shop",
    tags: ["Details", "Attributes"],
    tasks: [task("t30", "v29", "confirm_hours", "Are hours 11AM-11PM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-648-2300",
      hours: [{ day: "Daily", hours: "11 am - 11 pm" }],
      website: "http://www.mitchellsicecream.com",
      features: ["Cash and card", "Family owned"],
      fsqPlaceId: "3fd66200f964a520b3e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
      suggestedHours: [
        { day: "Sun - Thu", hours: "11 am - 10 pm" },
        { day: "Fri - Sat", hours: "11 am - 11 pm" },
      ],
    },
  },
  {
    id: "v30", name: "Plow", address: "1299 18th St, San Francisco, CA",
    lat: 37.7612, lng: -122.3903, category: "Breakfast Restaurant",
    tags: ["Categories", "Details"],
    tasks: [
      task("t31", "v30", "confirm_category", "Is 'Breakfast Restaurant' the correct category?", ["Yes", "No", "Not sure"]),
      task("t31b", "v30", "verify_address", "Is '1299 18th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-821-7569",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 3 pm" },
        { day: "Sat - Sun", hours: "8 am - 3:30 pm" },
      ],
      website: "http://www.eatatplow.com",
      instagram: "@eatatplow",
      features: ["Credit card: Visa, Master", "Outdoor seating"],
      fsqPlaceId: "4c86e9a58b3d2d7f2c64661c",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "1299 18th St, San Francisco, CA 94107",
    },
  },
];

export const INITIAL_COMPLETED_VENUES = [
  "v1", "v3", "v5", "v7", "v9",
  "v10", "v11", "v13", "v14", "v16",
  "v17", "v18", "v19", "v21", "v22",
];
